M48
; DRILL file {KiCad (6.0.4-0)} date Wednesday, September 21, 2022 at 04:47:22 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-21T16:47:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X148.5Y-225.6
X170.8Y-225.4
X172.7Y-218.5
X172.72Y-220.98
X197.6Y-222.4
T0
M30
